version: 2
updates:
- package-ecosystem: pip
  directory: "/src/movies-service"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.4.5
