version: '3.7'

services:
  movies_service:
    build: ./movies-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movies-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://q00Dree:q00Dree@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://casts_service:8000/api/v1/casts/

  movie_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=q00Dree
      - POSTGRES_PASSWORD=q00Dree
      - POSTGRES_DB=movie_db_dev

  casts_service:
    build: ./casts-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./casts-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://q00Dree:q00Dree@cast_db/cast_db_dev

  cast_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=q00Dree
      - POSTGRES_PASSWORD=q00Dree
      - POSTGRES_DB=cast_db_dev

volumes:
  postgres_data_movie:
  postgres_data_cast: