version: '3.7'

services:
  movie_service:
    build: ../src/movie-services
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ../src/movie-services/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://qoodree:qoodree@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/

  movie_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=qoodree
      - POSTGRES_PASSWORD=qoodree
      - POSTGRES_DB=movie_db_dev

  cast_service:
    build: ../src/cast-services
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ../src/cast-services/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://qoodree:qoodree@cast_db/cast_db_dev

  cast_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=qoodree
      - POSTGRES_PASSWORD=qoodree
      - POSTGRES_DB=cast_db_dev

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ../src/nginx/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service

volumes:
  postgres_data_movie:
  postgres_data_cast: